import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/next";
import "react-big-calendar/lib/css/react-big-calendar.css";
import "react-day-picker/dist/style.css";

import Providers from "@/providers/Providers";
import { geistMono, pretendard } from "@/styles/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Next.js, React, TypeScript" />
      </head>
      <body
        className={`${pretendard.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
        <Analytics />
      </body>
    </html>
  );
}
